/* Buckets' trash talk + court-side commentary. Confident playground energy,
   never mean-spirited, never profane. */
export const pick = (a) => a[Math.floor(Math.random() * a.length)];

export const T = {
  npcCall: [
    "From the chalk mark. Easy money.",
    "Watch the wrist, kid.",
    "This one's going on your tab.",
    "I warmed this spot up all morning.",
    "Net's about to sing.",
    "I've hit this shot in three different decades.",
    "You might wanna take notes.",
    "This spot? This spot loves me.",
    "Tell the fence to watch this.",
    "I dream about this shot. It goes in there too.",
    "Streetlights are coming on. That's my hour.",
    "Both eyes open for this one. You'll want the memory.",
  ],
  npcCallMod: {
    bank: [
      "Off the glass. Bank's open late tonight.",
      "Backboard first. Try to keep up.",
      "Glass, then cash.",
      "Bank shot called. I'm the teller.",
    ],
    moon: [
      "Moon ball. Sending it past the streetlights.",
      "Rainbow rules. High arc or it don't count.",
      "Moon ball called. NASA's watching.",
      "Put it in orbit or put it away.",
    ],
    nopreview: [
      "No preview. Shoot it from the soul.",
      "Eyes only. No training wheels.",
      "No dots. Real hoopers feel it.",
      "Blindfold rules. Well — no dots. Same thing.",
    ],
  },
  youCallMod: {
    bank: [
      "Bank shot called. He's gotta kiss the glass too.",
      "Off the glass or it doesn't count — for both of you.",
      "Bank's open. Make your deposit.",
    ],
    moon: [
      "Moon ball. You're both shooting rainbows now.",
      "High arc only. Send it to the clouds.",
      "Moon ball called. Mind the streetlights.",
    ],
    nopreview: [
      "No preview. You're both shooting blind.",
      "Dots off. Trust the wrist.",
      "No preview called. Feel it out.",
    ],
  },
  npcMake: [
    "Splash. Your ball, your problem.",
    "Wet. Now match it.",
    "That's bread. Copy that.",
    "All net. Don't choke.",
    "Cash. The register's still open.",
    "Butter. Now spread it yourself.",
    "Did the net even move? Exactly.",
    "That's how the textbook draws it.",
    "Same shot's waiting on you. Good luck.",
    "I could do that in a winter coat.",
  ],
  npcMiss: [
    "Rim's crooked. Always has been.",
    "Wind. Definitely wind.",
    "I get one mulligan, right? No? Fine.",
    "That was a warm-up.",
    "Ball's pumped wrong. Been saying it all day.",
    "That was on purpose. Keeping it close for you.",
    "Somebody moved the rim. I'm calling the city.",
    "Even the greats miss. Rarely. But it happens.",
    "My shoe's untied. Spiritually.",
    "Don't read anything into that.",
  ],
  npcMatched: [
    "Tch. Lucky bounce.",
    "Okay. You can play a little.",
    "Fine. FINE.",
    "Alright. One time's a coincidence.",
    "Mmhm. Even a broken clock.",
    "Cute. Do it when it matters.",
    "I left the door open. Won't happen twice.",
    "Okay okay. Somebody's been practicing.",
  ],
  npcLetter: [
    "Whatever. Letters are just ink.",
    "You won't do that twice.",
    "Enjoy it. It's the last one.",
    "Letters don't make buckets.",
    "I'm just keeping it interesting.",
    "That one's a gift. Receipt's in the bag.",
    "Scoreboard's wrong. Spiritually wrong.",
    "Even the alphabet's against me tonight.",
  ],
  youLetter: [
    "That letter looks heavy on you.",
    "Spell it with me now...",
    "I'd practice that one.",
    "Need me to spell the rest for you?",
    "That's a souvenir. Take it home.",
    "The fence saw that. The fence talks.",
    "You can quit now. Nobody'd blame you.",
    "I'd start stretching for the walk home.",
  ],
  youMakeSet: [
    "Your shot to match, Buckets.",
    "Money. Now he's gotta answer.",
    "Count it. Pressure's his now.",
    "Splash. Let's see him answer.",
    "That one kissed the net polite.",
    "Chalk that. He's on the clock.",
    "Clean. Buckets looks nervous. He'd deny it.",
    "Pure. Your spot now, Buckets.",
  ],
  youMissSet: [
    "Off the iron. Buckets takes over.",
    "Short. His ball now.",
    "Clank. He's grinning.",
    "Front rim. It happens. It keeps happening, but it happens.",
    "Air mail. Return to sender.",
    "That brick had a zip code.",
    "Rim said no thanks.",
    "He's already strolling to his spot.",
  ],
  youMatched: [
    "Matched him. He hates that.",
    "Answered. No letter today.",
    "Splash back. Right in his face.",
    "Answered like a doorbell.",
    "Matched it clean. He's rethinking things.",
    "You eat those for breakfast.",
  ],
  npcHot: [
    "I'm cooking now. Somebody call the fire department.",
    "Three straight. The rim owes me nothing tonight.",
    "I'm warmer than the asphalt in July.",
    "Heating up. You smell that? That's smoke.",
  ],
  youHot: [
    "Three in a row — you're heating up!",
    "The ball's glowing. That's all you.",
    "You're cooking. Buckets hates the smell.",
    "Hot hand! The rim just got friendly.",
  ],
  hotLostYou: [
    "Cooled off. The glow's gone.",
    "The streak dies there. Go get it back.",
    "Iced. Light the fire again.",
  ],
  hotLostNpc: [
    "Buckets cooled off. Hear that silence?",
    "The fire's out. He's furious.",
    "Streak's dead. He's blaming the wind.",
  ],
  gamePointYou: [
    "Letter five on the line. Breathe.",
    "Match it or walk home. No pressure.",
    "Everything rides on this one. Soft hands.",
  ],
  npcGamePoint: [
    "Match this and he walks home spelling it.",
    "One more letter and he's done. He knows it.",
  ],
  voidYou: {
    bank: [
      "It went in — but no glass. Doesn't count.",
      "Forgot the bank. The swish means nothing.",
    ],
    moon: [
      "Too flat. Moon ball means MOON ball.",
      "Line drive. The moon is up THERE.",
    ],
  },
  voidNpc: {
    bank: [
      "HA! No backboard. Buckets wasted a bucket.",
      "All net — which is exactly the problem. No glass, no cash.",
    ],
    moon: [
      "Flat as a pancake. Doesn't count, Buckets.",
      "He forgot the arc. The sky is disappointed.",
    ],
  },
  winText: [
    "Buckets spelled it. He says the sun was in his eyes — all five times.",
    "He's demanding a rematch and blaming the ball pressure.",
    "Buckets walked it off. He'll be back tomorrow. He's always back.",
  ],
  loseText: [
    "H-O-R-S-E. Buckets is already telling everyone at the fence.",
    "He's doing the slow clap. The disrespectful one.",
    "Spelled out. He says you can carry his bag next time.",
  ],
};
